export const APP_NAME = "LAST_CLICKER_7702";
export const VERSION = "1.0.3";
export const LOADING_MESSAGES = [
  "INITIALIZING EIP-7702...",
  "CONNECTING TO BLOCKCHAIN...",
  "LOADING GAME CONTRACT...",
  "ESTABLISHING SECURE LINK..."
];